language: python
python: 3.6
branches: master
install:
- pip install -r requirements.txt
script: true
before_deploy:
- mkdocs build --verbose --clean
deploy:
  provider: pages
  skip_cleanup: true
  github_token: "$github_token"
  local_dir: site
  on:
    branch: master
env:
  global:
    secure: a2M+npJQPB3slHXoTH5QayyeKEkwSw2Bhf4IuFoGDWI2JcNEJ0czHQkQBlS6k20VFqB3xRi9CZu6b7Ev791R2Wznmmeck+fApvZqRhTpCIrcDHsnGyQwNWsUCl+qx+Ycd/BF/fxGhXQj6z2ZjRKp8YCb6PNvVncurBmi/tZ5q/W8fICiMp+nqlE5Jnvw97NyAT4JvIXpyuzrOypzLKuEBqD7NFTVGx4dq45m9HtWUCOevdjUCbqa4bk9zcKhNrgcHXOSddOv+Kc8PsHbriYpAUKA3HPHuGAMkTmFGZMNEn4h/WfL+FcRga/pu78QiXK0cMsxnRi16PvnqJi8Pu26/oGXi+gstBnhV6FK6zZxcRMc3bL138g7REgDMocM1jBOBxyHBINM9j2gpFba/iG6voR/8ty6BCVBi8bVfHFt7tqCtVbz7WMP6r0admJPIfHh2R0kSei69MoYizuqWj7WJf9eKm3YHXMndNBerFbJwFBQe4McRx/kR7S1PLMj+s/njlv0kYZSu/uKb+mENs86BQyt3WFVIWOe113TMr6ZZfbkLjk2c8Cx2D9FUa4TbWNslTzkrvxlZSyo2JuDoPEX7uw6QV0ll4gsuoEY2crgQfBzQbHnWqZhSiQ8OTBKNEA5NjsUGqvkGMLFXvz6Au4JYqwbsHMItDaxV5ukJVKha84=
