language: python
python: 3.6
branches: master
install:
- pip install -r requirements.txt
script: true
before_deploy:
- mkdocs build --verbose --clean
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN
  local_dir: site
  on:
    branch: master
env:
  global:
    secure: WuA85sUMh3pNKnQIkywMw6xZGAd+Wwsrx5/flSSSaxvECV1uoRb6N4ayOH8IFjBCFkWseYx/xIr0D+OLLiTmPPoFKoRcnEODOjcN47mx0rmIG082dRpjKO7Qd+BuHwvbwlBrK87ARUlLKiucdsDoZfPwVOG02YsqUxGEE+hJh2ufyI6/RdVqYmYeYzkUw0RYaJMMaYNnwBnfqX/DzSop0z/k97doKhDG0334z5VMClD/thi9VJEQF1sF7DO86B44WOuGhTIDhhnj8PF/2NpmuN2V73xRBal7rJk61NXC6m2rvthsgWcKqrJTaz2QE5TAvuDL8SYgfiwwsh06UJjP0af+e0qx8uSR/VBre/HVJ4Ikag8vP0XQ68JlL6lMPEVOPf8WYr2E7nhmFFg+NrPKIViMJ7Ja85OYAz3OOqEz8vpJeTRwnMa/OVouVboe9vgJGy8KjP0MUoI6PGoQku1roFdWHCt++vBjZ9Xdq3L1eFhAxG18Pj3HtTAXrUoWiLN3VjaGEgHJlAz/OB/j3QXviAKbJ8mDEqNXV2msDzSGURvCTjihDyvmI6dr+Z72IT1TDP0iS0dK1b53pesN7cJdtGUncBQy7C43FELgN2//Q4egykDcurG1X44XVOph2UHYNKUlLF8XuXd5Yn63r4O9WEvOMXMMEgeny+nsQtKzHE4=
