site_name: APTrust User Guide
theme: material
markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
repo_url:  https://github.com/APTrust/userguide
nav:
  - Home: index.md
  - Quick Start:
      - index.md
      - first_deposit_with_dart.md
      - first_deposit_with_tools.md
  - Preservation Actions:
      - index.md
      - ingest.md
      - updates.md
      - restoration.md
      - deletion.md
  - Bagging:
      - index.md
      - tools.md
  - Using Pharos:
      - index.md
      - objects.md
      - files.md
      - events.md
      - work_items.md
      - user_management.md
      - two_factor_auth.md
      - rest_api.md
  - Glossary: glossary.md
  - Contact Us: contact_us.md
