site_name: APTrust User Guide
theme: material
extra_css:
  - 'stylesheets/extra.css'

markdown_extensions:
  - attr_list
  - admonition
  - codehilite
  - markdown_blockdiag:
      format: svg
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
repo_url:  https://github.com/APTrust/userguide
nav:
  - Home: index.md
  - Quick Start: quick_start.md
  - Preservation Actions:
      - preservation/ingest.md
      - preservation/updates.md
      - preservation/restoration.md
      - preservation/deletion.md
  - Bagging:
      - bagging/index.md
      - bagging/tools.md
  - Using Pharos:
      - pharos/index.md
      - pharos/objects.md
      - pharos/files.md
      - pharos/events.md
      - pharos/work_items.md
      - pharos/user_management.md
      - pharos/two_factor_auth.md
      - pharos/rest_api.md
  - Partner Tools: partner_tools.md
  - Registry:
      - registry/index.md
      - registry/api_changes.md
  - Glossary: glossary.md
  - Contact Us: contact_us.md
