site_name: APTrust User Guide
theme: material
markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
repo_url:  https://github.com/APTrust/userguide
nav:
  - Home: index.md
  - Quick Start:
      - quick_start/index.md
      - quick_start/first_deposit_with_dart.md
      - quick_start/first_deposit_with_tools.md
  - Preservation Actions:
      - preservation/index.md
      - preservation/ingest.md
      - preservation/updates.md
      - preservation/restoration.md
      - preservation/deletion.md
  - Bagging:
      - bagging/index.md
      - bagging/tools.md
  - Using Pharos:
      - pharos/index.md
      - pharos/objects.md
      - pharos/files.md
      - pharos/events.md
      - pharos/work_items.md
      - pharos/user_management.md
      - pharos/two_factor_auth.md
      - pharos/rest_api.md
  - Glossary: glossary.md
  - Contact Us: contact_us.md
