site_name: APTrust User Guide
theme: material
extra_css:
  - 'stylesheets/extra.css'

markdown_extensions:
  - attr_list
  - admonition
  - codehilite
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
repo_url:  https://github.com/APTrust/userguide
nav:
  - Home: index.md
  - Quick Start: quick_start.md
  - Preservation Actions:
      - preservation/ingest.md
      - preservation/updates.md
      - preservation/restoration.md
      - preservation/deletion.md
  - Depositing:
      - depositing/index.md
      - depositing/tools.md
      - depositing/guidelines.md
  - Using Registry:
      - registry/index.md
      - registry/objects.md
      - registry/files.md
      - registry/events.md
      - registry/work_items.md
      - registry/user_management.md
      - registry/two_factor_auth.md
      - registry/spot_tests.md
      - registry/reports.md
      - registry/rest_api.md
      - registry/api_changes.md
  - Partner Tools: partner_tools.md
  - Old Partner Tools: old_partner_tools.md
  - Glossary: glossary.md
  - Contact Us: contact_us.md
plugins:
  - redirects:
      redirect_maps:
        'bagging/index.md': 'depositing/index.md'
        'bagging/tools.md': 'depositing/tools.md'
        #'some_file.md': 'http://external.url.com/foobar'